name: 'Issue Enhancer Agent'
description: 'An AI-powered GitHub Action that enhances issue descriptions, comments, and labels using Semantic Kernel and Azure OpenAI.'
author: 'mattdot'

branding:
  icon: 'shield'
  color: 'blue'

runs:
  using: 'docker'
  image: 'Dockerfile'

inputs:
  github_token:
    description: 'GitHub token with repo access (defaults to github.token)'
    required: false
    default: ${{ github.token }}
  azure_openai_target_uri:
    description: 'Azure OpenAI target URI'
    required: true
  azure_openai_api_key:
    description: 'API key for Azure OpenAI'
    required: true

outputs:
  status:
    description: 'Status of the operation'