name: Python Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort detect-secrets
      - name: Run flake8
        run: |
          flake8 src/ --max-line-length=120
      - name: Run black
        run: |
          black --check src/
      - name: Run isort
        run: |
          isort --check-only src/
      - name: Check for secrets
        run: |
          detect-secrets scan --all-files
